apiVersion: v1
kind: Service
metadata:
  name: app-vert-{{ .Release.Name }}
  namespace: {{ .Values.nameSpace }}
spec:
  clusterIP: None
  selector:
    app: app-vert-{{ .Release.Name }}
  ports:
    - name: vert 
      protocol: TCP
      port: {{ .Values.apache2.container.port }}
      targetPort: {{ .Values.apache2.container.port }}
