apiVersion: v1
kind: Service
metadata:
  name: app-marronvert-{{ .Release.Name }}
  namespace: {{ .Values.nameSpace }}
#  le lb par defaut est classic lb
  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: app-marronvert-{{ .Release.Name }}
  type: LoadBalancer
  ports:
    - name: port1
      protocol: TCP
      port: {{ .Values.nginx.container.port }}
      targetPort: {{ .Values.nginx.container.port }}

