apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ .Release.Name }}
  namespace: {{ .Values.nameSpace }}
data:
{{ tpl (.Files.Glob "files/nginx.conf").AsConfig . | indent 4 }}
#!!! l'indent de la ligne ci-dessus doit etre a la hauteur de "data"
